apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops
  labels:
    app: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: devopsregistryhenry2025.azurecr.io/devops-microservice:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "clave_super_secreta_segura"
        - name: API_KEY
          value: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
      imagePullSecrets:
      - name: acr-credentials
