apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: devops
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESS_STICKY"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <HOST>
      secretName: devops-tls
  rules:
    - host: <HOST>
      http:
        paths:
          # Ruta general: expone /, por lo que /DevOps y /generate-jwt pasan tal cual
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-service
                port:
                  number: 80
