apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
  namespace: devops
type: Opaque
stringData:
  SECRET_KEY: clave_super_secreta_segura
  API_KEY: 2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
