apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
  namespace: devops
type: Opaque
data:
  SECRET_KEY: Y2xhdmUtc3VwZXItc2VjcmV0YS1zZWd1cmE=               # base64 de clave_super_secreta_segura
  API_KEY: MnI1YWU5NmMtYjU1OC00YzdiLWE1OTAtYTUwMWFlMWMxZjNj  # base64 de 2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
